var English = {
    "We are the future of gaming": "We are the future of gaming",
    "Username": "Username",
    "Password": "Password",
    "Captcha": "Captcha",
    "Sign in": "Sign In",
    "Contact your associate in case you forgot the password or unable to sign in": "Contact your associate in case you forgot the password or unable to sign in",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;Mobile Version",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;Guide",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;Log Out",
    "Dashboard": "Dashboard",
    "Member Mngement": "Management",
    "Stock Mngement": "Stock Management",
    "Balance info": "Balance info",
    "Today Turn Over": "Today Turn Over",
    "Today Valid Turn Over": "Today Valid Turn Over",
    "Today Member Win Lose": "Today Member Win Lose",
    "Today Agent Win Lose": "Today Agent Win Lose",
    "Yesterday Turn Over": "Yesterday Turn Over",
    "Yesterday Valid Turn Over": "Yesterday Valid Turn Over",
    "Yesterday Member Win Lose": "Yesterday Member Win Lose",
    "Yesterday Agent Win Lose": "Yesterday Agent Win Lose",
    "Total Outstanding Bets": "Total Outstanding Bets",
    "Total Outstanding Balance": "Total Outstanding Balance",
    "Members": "Members",
    "Agents": "Agents",
    "Today": "Today",
    "Last Week": "Last Week",
    "Last Month": "Last Month",
    "Outstanding": "Outstanding",
    "Your Downline": "Your Downline",
    "New Members": "New Members",
    "Profile": "Profile",
    "Basic Info": "Basic Info",
    "Phone number": "Phone number",
    "Currency": "Currency",
    "Credit": "Credit",
    "PT": "PT",
    "Original Baccarat": "Original Baccarat",
    "Super6 Baccarat": "Super6 Baccarat",
    "Bacarrat 4 Point": "Bacarrat 4 Point",
    "Cow Cow": "Cow Cow",
    "Dragon Tiger": "Dragon Tiger",
    "Roulete": "Roulete",
    "Sicbo": "Sicbo",
    "Thai Fan Tan": "Thai Fan Tan",
    "Original Baccarat_": "Original Baccarat :",
    "Super6 Baccarat_": "Super6 Baccarat :",
    "Bacarrat 4 Point_": "Bacarrat 4 Point :",
    "Cow Cow_": "Cow Cow :",
    "Dragon Tiger_": "Dragon Tiger :",
    "Roulete_": "Roulete :",
    "Sicbo_": "Sicbo :",
    "Key": "Key",
    "Callback url servlet": "Callback url servlet",
    "Example https//www.yourcallback.com/service": "Example: https://www.yourcallback.com/service",
    "IP": "IP",
    "Example 192.168.0.1": "Example: 192.168.0.1",
    "Click to API Document": "Click to API Document",
    "Add IP": "Add IP",
    "Save Profile": "Save Profile",
    "History login date & IP": "History login date & IP",
    "Date": "Date",
    "IP address": "IP address",
    "Commission": "Commission",
    "Change Password": "Change Password",
    "Save New Password": "Save New Password",
    "Add Sub Account": "Add Sub Account",
    "Login name": "Login name",
    "Login name_": "Login name :",
    "User_": "Company :",
    "Search": "Search",
    "No": "No",
    "Nickname": "Nickname",
    "Phone": "Phone",
    "Edit": "Edit",
    "Lock": "Lock",
    "Member": "Member",
    "Stock": "Stock",
    "Report": "Report",
    "Last login date": "Last login date",
    "Last login IP": "Last login IP",
    "Last login IP_": "Last login IP :",
    "Permissions": "Permissions",
    "Off": "Off",
    "View": "View",
    "OFF": "OFF",
    "VIEW": "VIEW",
    "EDIT": "EDIT",
    "Position": "Position",
    "Stake": "Stake",
    "Turnover": "Turnover",
    "Company Total": "Company Total",
    "Company": "Company",
    "Agent": "Agent",
    "Agent (API)": "Agent (API)",
    "Total": "Total :",
    "Total-": "Total",
    "Member Total": "Member Total",
    "Agent Total": "Agent Total",
    "Event & Details": "Event & Details",
    "No data.": "No data.",
    "Login date": "Login date",
    "Login IP": "Login IP",
    "Bet": "Bet",
    "Bet Type": "Bet Type",
    "Bet Type_": "Bet Type :",
    "Settle": "Settle",
    "Seamless API": "Seamless API",
    "Recalculate": "Recalculate",
    "Ticket ID": "Ticket ID",
    "Ticket ID_": "Ticket ID :",
    "Request / Response": "Request / Response",
    "Retry": "Retry",
    "User Place Payout": "User Place Payout",
    "User Place Bet Cancel": "User Place Bet Cancel",
    "User Place Bet": "User Place Bet",
    "Announcements": "Announcements",
    "Message": "Message",
    "Description": "Description",
    "Add Message": "Add Message",
    "Add Message_": "<i class='fas fa-plus mr-1'></i>Add Message",
    "Add Banner_": "<i class='fas fa-plus mr-1'></i>Add Banner",
    "Create date": "Create date",
    "Create date_": "Create date :",
    "Modify date": "Modify date",
    "Update by": "Update by",
    "Delete": "Delete",
    "Title": "Title",
    "Title_": "Title :",
    "Banner": "Banner",
    "Add Banner": "Add Banner",
    "Image": "Image",
    "Payment": "Payment",
    "Deposit / Withdrawal": "Deposit / Withdrawal",
    "Credit": "Credit",
    "Credit_": "Credit :",
    "Level": "Level",
    "Level_": "Level :",
    "Deposit": "Deposit",
    "Withdrawal": "Withdrawal",
    "Detail": "Detail",
    "Account": "Account",
    "Member Management": "Member Management",
    "Sub Accounts": "Sub Accounts",
    "Unlock": "Unlock",
    "Stock Management": "Stock Management",
    "Member Outstanding": "Member Outstanding",
    "Statement": "Statement",
    "Start date_": "Start date :",
    "To date_": "To date :",
    "Action": "Action",
    "Total balance": "Total balance",
    "Log": "Log",
    "All": "All",
    "Previous": "Previous",
    "Yesterday": "Yesterday",
    "This week": "This week",
    "Last week": "Last week",
    "This month": "This month",
    "Last month": "Last month",
    "Next": "Next",
    "Description_": "Description :",
    "Description-": "Description&nbsp;<label style='color: red;'>*</label>",
    "Suspend": "Suspend",
    "Add Shareholder": "Add Shareholder",
    "Shareholder": "Shareholder",
    "Shareholder (B2B)": "Shareholder (B2B)",
    "Shareholder (B2C)": "Shareholder (B2C)",
    "NoSus": "No",
    "YesSus": "Yes",
    "Username-": "Username<label style='color: red;'>&nbsp;*</label>",
    "Password-": "Password<label style='color: red;'>&nbsp;*</label>",
    "Currency-": "Currency<label style='color: red;'>&nbsp;*</label>",
    "Credit-": "Credit<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type-": "Shareholder type<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type": "Type",
    "Our PT-": "Our PT<label style='color: red;'>&nbsp;*</label>",
    "Our PT": "Our PT",
    "Given PT-": "Given PT<label style='color: red;'>&nbsp;*</label>",
    "Given PT": "Given PT",
    "Original Baccarat-": "Original Baccarat<label style='color: red;'>&nbsp;*</label>",
    "Super6 Baccarat-": "Super6 Baccarat<label style='color: red;'>&nbsp;*</label>",
    "Bacarrat 4 Point-": "Bacarrat 4 Point<label style='color: red;'>&nbsp;*</label>",
    "Cow Cow-": "Cow Cow<label style='color: red;'>&nbsp;*</label>",
    "Dragon Tiger-": "Dragon Tiger<label style='color: red;'>&nbsp;*</label>",
    "DragonTiger": "Dragon Tiger",
    "Roulete-": "Roulete<label style='color: red;'>&nbsp;*</label>",
    "Sicbo-": "Sicbo<label style='color: red;'>&nbsp;*</label>",
    "Commission Setting": "Commission Setting",
    "Credit Settings": "Credit Settings",
    "Edit Password": "Edit Password",
    "Edit Status": "Edit Status",
    "Edit Shareholder": "Edit Shareholder",
    "Status": "Status",
    "Members & Agents": "Members & Agents",
    "Position type-": "Position type<label style='color: red;'>&nbsp;*</label>",
    "Bet type-": "Bet type<label style='color: red;'>&nbsp;*</label>",
    "Add Agent": "Add Agent",
    "Edit Agent": "Edit Agent",
    "Position type": "Position type",
    "Bet Limit-": "Bet Limit<label style='color: red;'>&nbsp;*</label>",
    "Bet Limit": "Bet Limit",
    "Add Member": "Add Member",
    "Edit Member": "Edit Member",
    "Transaction_": "Transaction :",
    "W/L Member": "W/L Member",
    "W/L Game ID": "W/L Game ID",
    "W/L Company": "W/L Company",
    "Valid turn": "Valid turn",
    "Amount": "Amount",
    "Gross Comm": "Gross Comm",
    "Win lose": "Win lose",
    "Comm": "Comm",
    "Information": "Information",
    "Result": "Result",
    "Credit/Cash": "Credit/Cash",
    "Partner": "Partner",
    "Win/Loss & Comm & Total": "Win/Loss & Comm & Total",
    "User": "User",
    "ID": "ID",
    "Game ID": "Game ID",
    "Game ID_": "Game ID :",
    "Baccarat": "Baccarat",
    "tie": "tie",
    "player": "player",
    "banker": "banker",
    "Original": "Original",
    "Play Clip": "&nbsp;Play Clip",
    "Before": "Before",
    "Win/Loss": "Win/Loss",
    "After": "After",
    "Lose": "Lose",
    "Win": "Win",
    "Tie": "Tie",
    "Player": "Player",
    "Banker": "Banker",
    "Super6": "Super6",
    "CowCow": "CowCow",
    "4Point": "4Point",
    "Old Password": "Old Password<label style='color: red;'>&nbsp;*</label>",
    "New Password": "New Password<label style='color: red;'>&nbsp;*</label>",
    "Confirm Password": "Confirm Password<label style='color: red;'>&nbsp;*</label>",
    "missing 'Old Password' field": "Please enter 'Old Password'",
    "missing 'New Password' field": "Please enter 'New Password'",
    "missing 'Confirm Password' field": "Please enter 'Confirm Password'",
    "New password doesn't match confirm password": "New password doesn't match confirm password",
    "Close": "Close",
    "Change new password success": "Change new password success",
    "Success": "Success",
    "Save profile success": "Save profile success",
    "missing 'Username' field": "Please enter 'Username'",
    "missing 'Password' field": "Please enter 'Password'",
    "missing 'Captcha' field": "Please enter 'Captcha'",
    "missing 'Currency' field": "Please select 'Currency'",
    "missing 'Credit' field": "Please enter 'Credit'",
    "Save add new agent success": "Save add new agent success",
    "Request By": "Request By",
    "Save": "Save",
    "Edit Message": "Edit Message",
    "Confirm delete this item ?": "Confirm delete this item ?",
    "Delete Message": "Delete Message",
    "OK": "OK",
    "missing 'Description' field": "Please enter 'Description'",
    "Add new message success": "Add new message success",
    "Edit message succes": "Edit message succes",
    "Delete message success": "Delete message success",
    "Title-": "Title&nbsp;<label style='color: red;'>*</label>",
    "Image-": "Image&nbsp;<label style='color: red;'>*</label>",
    "Edit Banner": "Edit Banner",
    "Delete Banner": "Delete Banner",
    "missing 'Image' field": "Please browse file 'Image'",
    "missing 'Title' field": "Please enter 'Title'",
    "Add new banner success": "Add new banner success",
    "Edit banner success": "Edit banner success",
    "Delete banner success": "Delete banner success",
    "Delete sub account success": "Delete sub account success",
    "Account-": "Account :",
    "Deposit-": "Deposit :",
    "Currency_": "Currency :",
    "Withdrawal-": "Withdrawal :",
    "History Detail": "History Detail",
    "Agent": "Agent",
    "Member": "Member",
    "Update deposit success": "Update deposit success",
    "Update withdrawal success": "Update withdrawal success",
    "DEPOSIT": "DEPOSIT",
    "WITHDRAWAL": "WITHDRAWAL",
    "Save add new shareholder success": "Save add new shareholder success",
    "Suspend-": "Suspend :",
    "Lock-": "Lock :",
    "Edit status suspend, lock success": "Edit status suspend, lock success",
    "Edit sub account success": "Edit sub account success",
    "Save add new sub account success": "Save add new sub account success",
    "Edit agent success": "Edit agent success",
    "Edit member success": "Edit member success",
    "Edit shareholder success": "Edit shareholder success",
    "Save add new member success": "Save add new member success",
    "missing 'Bet Limit' field": "Please select 'Bet Limit'",
    "History Edit": "History Edit",
    "Online": "Online : ",
    "Min": "Min",
    "Max": "Max",
    "Invalid Currency": "Invalid Currency",
    "Bet Status": "Bet Status",
    "Seamless Status": "Seamless Status",
    "Request List": "Request List",
    "Logs": "Logs",
    "Edit by": "Edit by",
    "textnumberonly": "Enter only number (0-9) or letter (A-Z, a-z).",
    "numberonly": "Enter only number (0-9).",
    "textTHnumberonly": "Enter only number (0-9) or letter (A-Z, a-z, ก-ฮ).",
    "Invalid Username or Password": "Invalid Username or Password",
    "You've entered incorrect password too many times. Try again in 5 minutes.": "You've entered incorrect password too many times. Try again in 5 minutes.",
    "Invalid captcha.": "Invalid captcha.",
    "Dragon": "Dragon",
    "Tiger": "Tiger",
    "big": "big",
    "bankerPair": "bankerPair",
    "bankerNatural": "bankerNatural",
    "playerNatural": "playerNatural",
    "playerPair": "playerPair",
    "small": "small",
    "super6": "super6",
    "The old password you have entered is incorrect.": "The old password you have entered is incorrect.",
    "Invalid input format 'password' field. (The password must have at least 8 characters.)": "Invalid input format 'password' field. (The password must have at least 8 characters.)",
    "Invalid input format 'username' field. (The username must have at least 8 characters.)": "Invalid input format 'username' field. (The username must have at least 8 characters and don't enter special characters.)",
    "Can't load report, because you refresh more than 30 times.": "Can't load report, because you refresh more than 30 times. Please try again in 1 minute.",
    "Insufficient balance.": "Insufficient balance.",
    "missing 'date' field": "Please select 'Start date' and 'To date'",
    "invalid bet limit parameter please input bet limit more than 1 but not more than 6 value.": "Please input bet limit more than 1 but not more than 6 value.",
    "E11000 duplicate key error collection": "Username is duplicate.",
    "dragon": "Dragon",
    "tiger": "Tiger",
    "No.Ticket": "No.Ticket",
    "Rate": "Rate",
    "Comment": "Comment",
    "Network Connection": "Network Connection",
    "Video Quality": "Video Quality",
    "Our Girls": "Our Girls",
    "Graphic Design": "Graphic Design",
    "Customer Service": "Customer Service",
    "Member W/L": "Member W/L",
    "House Edge": "House Edge",
    "Export Excel": "Export Excel",
    "ExportNote": "Remark: limit to 100 records per download",
    "Login name not found.": "Login name not found.",
    "Tip Dealer": "Tip Dealer",
    "Callback Dealer Tips": "Callback Dealer Tips",
    "Tips": "Tips",
    "Type_": "Type :",
    "Open": "Open",
    "Close": "Close",
    "Setting Baccarat": "Setting Baccarat"
};

var Thai = {
    "We are the future of gaming": "พวกเราคืออนาคตของเกมออนไลน์",
    "Username": "ชื่อผู้ใช้",
    "Password": "รหัสผ่าน",
    "Captcha": "Captcha",
    "Sign in": "เข้าสู่ระบบ",
    "Contact your associate in case you forgot the password or unable to sign in": "ติดต่อตัวแทนของคุณในกรณีที่คุณลืมรหัสผ่านหรือไม่สามารถลงชื่อเข้าใช้ได้",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;เวอร์ชั่นมือถือ",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;คู่มือการใช้งาน",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;ออกจากระบบ",
    "Dashboard": "รายละเอียดของคุณ",
    "Member Mngement": "การจัดการสมาชิก",
    "Stock Mngement": "การจัดการสต็อก",
    "Balance info": "ข้อมูลยอดคงเหลือ",
    "Today Turn Over": "ยอดเล่นวันนี้",
    "Today Valid Turn Over": "ยอดเล่นจริงวันนี้",
    "Today Member Win Lose": "สมาชิกแพ้ชนะวันนี้",
    "Today Agent Win Lose": "เอเย่นต์แพ้ชนะวันนี้",
    "Yesterday Turn Over": "ยอดเล่นเมื่อวาน",
    "Yesterday Valid Turn Over": "ยอดเล่นจริงเมื่อวาน",
    "Yesterday Member Win Lose": "สมาชิกแพ้ชนะเมื่อวาน",
    "Yesterday Agent Win Lose": "เอเย่นต์แพ้ชนะเมื่อวาน",
    "Total Outstanding Bets": "การเดิมพันยอดคงค้างทั้งหมด",
    "Total Outstanding Balance": "ยอดคงค้างทั้งหมด",
    "Members": "สมาชิก",
    "Agents": "เอเย่นต์",
    "Today": "วันนี้",
    "Last Week": "อาทิตย์ที่แล้ว",
    "Last Month": "เดือนที่แล้ว",
    "Outstanding": "ยอดคงค้าง",
    "Your Downline": "ดาวน์ไลน์ของคุณ",
    "New Members": "สมาชิกใหม่",
    "Profile": "ข้อมูลส่วนตัว",
    "Basic Info": "ข้อมูลพื้นฐาน",
    "Phone number": "เบอร์โทรศัพท์",
    "Currency": "สกุลเงิน",
    "Credit": "ยอดเงิน",
    "Credit_": "ยอดเงิน :",
    "PT": "เปอร์เซนต์ถือสู้",
    "Original Baccarat": "บาคาร่าทั่วไป",
    "Super6 Baccarat": "ซุปเปอร์ซิกบาคาร่า",
    "Bacarrat 4 Point": "บาคาร่าน้ำ4ตังค์",
    "Cow Cow": "วัว วัว",
    "Dragon Tiger": "เสือ มังกร",
    "Roulete": "รูเล็ท",
    "Sicbo": "ซิกโบ",
    "Thai Fan Tan": "ถั่ว",
    "Original Baccarat_": "บาคาร่าทั่วไป :",
    "Super6 Baccarat_": "ซุปเปอร์ซิกบาคาร่า :",
    "Bacarrat 4 Point_": "บาคาร่าน้ำ4ตังค์ :",
    "Cow Cow_": "วัว วัว :",
    "Dragon Tiger_": "เสือ มังกร :",
    "DragonTiger": "เสือ มังกร",
    "Roulete_": "รูเล็ท :",
    "Sicbo_": "ซิกโบ :",
    "Key": "คีย์",
    "Callback url servlet": "ลิ้งตอบกกลับ",
    "Example https//www.yourcallback.com/service": "ตัวอย่าง: https://www.yourcallback.com/service",
    "IP": "ไอพี",
    "Example 192.168.0.1": "ตัวอย่าง: 192.168.0.1",
    "Click to API Document": "คลิกไปที่เอกสาร API",
    "Add IP": "เพิ่มไอพี",
    "Save Profile": "บันทึกข้อมูลส่วนตัว",
    "History login date & IP": "ประวัติวันที่เข้าสู่ระบบและไอพี",
    "Date": "วันที่",
    "IP address": "ไอพีแอดเดรส",
    "Commission": "ค่าคอม",
    "Change Password": "เปลี่ยนรหัสผ่าน",
    "Save New Password": "บันทึกรหัสผ่านใหม่",
    "Add Sub Account": "เพิ่มบัญชีย่อย",
    "Login name": "ชื่อเข้าสู่ระบบ",
    "Login name_": "ชื่อเข้าสู่ระบบ :",
    "User_": "คอมพานี :",
    "Search": "ค้นหา",
    "No": "ลำดับ",
    "Nickname": "ชื่อเล่น",
    "Phone": "เบอร์โทร",
    "Edit": "แก้ไข",
    "Lock": "ล็อค",
    "Member": "สมาชิก",
    "Stock": "สต็อค",
    "Report": "รายงาน",
    "Last login date": "วันที่ล็อคอินล่าสุด",
    "Last login IP": "IP ล็อคอินล่าสุด",
    "Last login IP_": "IP ล็อคอินล่าสุด :",
    "Permissions": "สิทธิ์",
    "Off": "ปิด",
    "View": "ดู",
    "OFF": "ปิด",
    "VIEW": "ดู",
    "EDIT": "แก้ไข",
    "Position": "ตำแหน่ง",
    "Stake": "เดิมพัน",
    "Turnover": "ยอดเล่น",
    "Company Total": "ยอดรวมของบริษัท",
    "Company": "บริษัท",
    "Agent": "เอเย่นต์",
    "Agent (API)": "เอเย่นต์ (API)",
    "Total": "ทั้งหมด :",
    "Total-": "ทั้งหมด",
    "Member Total": "ยอดรวมสมาชิก",
    "Agent Total": "ยอดรวมเอเย่นต์",
    "Event & Details": "กิจกรรมและรายละเอียด",
    "No data.": "ไม่มีข้อมูล.",
    "Login date": "วันที่เข้าสู่ระบบ",
    "Login IP": "ไอพีเข้าสู่ระบบ",
    "Bet Type_": "ประเภทการเล่น :",
    "Settle": "คิดเงิน",
    "Bet": "เดิมพัน",
    "Bet Type": "ประเภทการเล่น",
    "Seamless API": "API แบบกระเป๋าเดียว",
    "Recalculate": "คำนวณใหม่",
    "Ticket ID": "รหัสตั๋ว",
    "Ticket ID_": "รหัสตั๋ว :",
    "Request / Response": "คำขอ / ตอบกลับ",
    "Retry": "ลองใหม่",
    "User Place Payout": "การชำระเงินของผู้ใช้",
    "User Place Bet Cancel": "ผู้ใช้ยกเลิกเดิมพัน",
    "User Place Bet": "ผู้ใช้วางเดิมพัน",
    "Announcements": "ประกาศ",
    "Message": "ข้อความข่าวสาร",
    "Description": "คำอธิบาย",
    "Add Message": "เพิ่มข้อความข่าวสาร",
    "Add Message_": "<i class='fas fa-plus mr-1'></i>เพิ่มข้อความข่าวสาร",
    "Create date": "วันที่สร้าง",
    "Create date_": "วันที่สร้าง :",
    "Modify date": "วันที่แก้ไข",
    "Update by": "อัปเดตโดย",
    "Delete": "ลบ",
    "Title": "ชื่อ",
    "Title_": "ชื่อ :",
    "Banner": "แบนเนอร์",
    "Add Banner": "เพิ่มแบนเนอร์",
    "Image": "รูปภาพ",
    "Payment": "การชำระเงิน",
    "Deposit / Withdrawal": "ฝาก / ถอน",
    "Credit": "ยอดเงิน",
    "Level": "ระดับ",
    "Deposit": "ฝากเงิน",
    "Withdrawal": "ถอนเงิน",
    "Detail": "รายละเอียด",
    "Account": "บัญชีผู้ใช้",
    "Member Management": "การจัดการสมาชิก",
    "Sub Accounts": "บัญชีย่อย",
    "Unlock": "ปลดล็อค",
    "Stock Management": "การจัดการสต็อก",
    "Member Outstanding": "รายการสมาชิกคงค้าง",
    "Statement": "รายงานการเงิน",
    "Start date_": "วันที่เริ่มต้น :",
    "To date_": "ถึงวันที่ :",
    "Action": "ประเภท",
    "Total balance": "ยอดรวม",
    "Log": "ข้อมูลบันทึก",
    "All": "ทั้งหมด",
    "Previous": "ก่อนหน้า",
    "Yesterday": "เมื่อวานนี้",
    "This week": "สัปดาห์นี้",
    "Last week": "สัปดาห์ที่แล้ว",
    "This month": "เดือนนี้",
    "Last month": "เดือนที่แล้ว",
    "Next": "ถัดไป",
    "Description_": "คำอธิบาย :",
    "Suspend": "ระงับชั่วคราว",
    "Level_": "ระดับ :",
    "Add Shareholder": "เพิ่มตัวแทน",
    "Shareholder": "ตัวแทน",
    "Shareholder (B2B)": "ตัวแทน (B2B)",
    "Shareholder (B2C)": "ตัวแทน (B2C)",
    "NoSus": "ไม่ใช่",
    "YesSus": "ใช่",
    "Username-": "ชื่อผู้ใช้<label style='color: red;'>&nbsp;*</label>",
    "Password-": "รหัสผ่าน<label style='color: red;'>&nbsp;*</label>",
    "Currency-": "สกุลเงิน<label style='color: red;'>&nbsp;*</label>",
    "Credit-": "ยอดเงิน<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type-": "ประเภทตัวแทน<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type": "ประเภทตัวแทน",
    "Our PT-": "เปอร์เซนต์ของเรา<label style='color: red;'>&nbsp;*</label>",
    "Our PT": "เปอร์เซนต์ของเรา",
    "Given PT-": "ให้เปอร์เซนต์<label style='color: red;'>&nbsp;*</label>",
    "Given PT": "ให้เปอร์เซนต์",
    "Original Baccarat-": "บาคาร่าทั่วไป<label style='color: red;'>&nbsp;*</label>",
    "Super6 Baccarat-": "ซุปเปอร์ซิกบาคาร่า<label style='color: red;'>&nbsp;*</label>",
    "Bacarrat 4 Point-": "บาคาร่าน้ำ4ตังค์<label style='color: red;'>&nbsp;*</label>",
    "Cow Cow-": "วัว วัว<label style='color: red;'>&nbsp;*</label>",
    "Dragon Tiger-": "เสือ มังกร<label style='color: red;'>&nbsp;*</label>",
    "Roulete-": "รูเล็ท<label style='color: red;'>&nbsp;*</label>",
    "Sicbo-": "ซิกโบ<label style='color: red;'>&nbsp;*</label>",
    "Commission Setting": "ตั้งค่าค่าคอม",
    "Credit Settings": "ตั้งค่ายอดเงิน",
    "Edit Password": "แก้ไขรหัสผ่าน",
    "Edit Status": "แก้ไขสถานะ",
    "Edit Shareholder": "แก้ไขตัวแทน",
    "Status": "สถานะ",
    "Members & Agents": "สมาชิกและเอเย่นต์",
    "Position type-": "ตำแหน่งประเภท<label style='color: red;'>&nbsp;*</label>",
    "Bet type-": "ประเภทการเดิมพัน<label style='color: red;'>&nbsp;*</label>",
    "Add Agent": "เพิ่มเอเย่นต์",
    "Edit Agent": "แก้ไขเอเย่นต์",
    "Position type": "ประเภทตำแหน่ง",
    "Bet Limit-": "วงเงินเดิมพัน<label style='color: red;'>&nbsp;*</label>",
    "Bet Limit": "วงเงินเดิมพัน",
    "Add Member": "เพิ่มสมาชิก",
    "Edit Member": "แก้ไขสมาชิก",
    "Add Banner_": "<i class='fas fa-plus mr-1'></i>เพิ่มแบนเนอร์",
    "Transaction_": "รายการเงิน :",
    "W/L Member": "แพ้ชนะสมาชิก",
    "W/L Game ID": "แพ้ชนะเกมส์ไอดี",
    "W/L Company": "แพ้ชนะคอมพานี",
    "Valid turn": "ยอดเล่นจริง",
    "Amount": "จำนวน",
    "Gross Comm": "ค่าคอม",
    "Win lose": "แพ้ชนะ",
    "Comm": "ค่าคอม",
    "Information": "ข้อมูล",
    "Result": "ผลลัพธ์",
    "Credit/Cash": "ยอดเงิน/เงินสด",
    "Partner": "หุ้นส่วน",
    "Win/Loss & Comm & Total": "แพ้/ชนะ และ คอม และ ทั้งหมด",
    "User": "ผู้ใช้งาน",
    "ID": "ไอดี",
    "Game ID": "เกมไอดี",
    "Game ID_": "เกมไอดี :",
    "Baccarat": "บาคาร่า",
    "tie": "เสมอ",
    "player": "เพลย์เยอร์",
    "banker": "แบงค์เกอร์",
    "Original": "ออริจินอล",
    "Play Clip": "&nbsp;เล่นวิดีโอ",
    "Before": "ก่อน",
    "Win/Loss": "ชนะ/แพ้",
    "After": "หลัง",
    "Lose": "เสีย",
    "Win": "ชนะ",
    "Tie": "เสมอ",
    "Player": "เพลย์เยอร์",
    "Banker": "แบงค์เกอร์",
    "Super6": "ซุปเปอร์ซิก",
    "CowCow": "วัว วัว",
    "4Point": "4 ตังค์",
    "Old Password": "รหัสผ่านเดิม<label style='color: red;'>&nbsp;*</label>",
    "New Password": "รหัสผ่านใหม่<label style='color: red;'>&nbsp;*</label>",
    "Confirm Password": "ยืนยันรหัสผ่านใหม่<label style='color: red;'>&nbsp;*</label>",
    "missing 'Old Password' field": "กรุณากรอก 'รหัสผ่านเดิม'",
    "missing 'New Password' field": "กรุณากรอก 'รหัสผ่านใหม่'",
    "missing 'Confirm Password' field": "กรุณากรอก 'ยืนยันรหัสผ่าน'",
    "New password doesn't match confirm password": "รหัสผ่านใหม่ไม่ตรงกับรหัสผ่านยืนยัน",
    "Close": "ปิด",
    "Change new password success": "เปลี่ยนรหัสผ่านใหม่สำเร็จ",
    "Success": "สำเร็จ",
    "Save profile success": "บันทึกข้อมูลส่วนตัวสำเร็จ",
    "missing 'Username' field": "กรุณากรอก 'ชื่อผู้ใช้'",
    "missing 'Password' field": "กรุณากรอก 'รหัสผ่าน'",
    "missing 'Captcha' field": "กรุณากรอก 'Captcha'",
    "missing 'Currency' field": "กรุณาเลือก 'สกุลเงิน'",
    "missing 'Credit' field": "กรุณากรอก 'ยอดเงิน'",
    "Save add new agent success": "บันทึกเอเย่นต์ใหม่สำเร็จ",
    "Request By": "ขอโดย",
    "Description-": "คำอธิบาย&nbsp;<label style='color: red;'>*</label>",
    "Save": "บันทึก",
    "Edit Message": "แก้ไขข้อความข่าวสาร",
    "Confirm delete this item ?": "ยืนยันการลบรายการนี้ ?",
    "Delete Message": "ลบข้อความข่าวสาร",
    "OK": "ยืนยัน",
    "missing 'Description' field": "กรุณากรอก 'คำอธิบาย'",
    "Add new message success": "เพิ่มข้อความข่าวสารใหม่สำเร็จ",
    "Edit message succes": "แก้ไขข้อความข่าวสารสำเร็จ",
    "Delete message success": "ลบข้อความข่าวสารสำเร็จ",
    "Title-": "ชื่อ&nbsp;<label style='color: red;'>*</label>",
    "Image-": "รูปภาพ&nbsp;<label style='color: red;'>*</label>",
    "Edit Banner": "แก้ไขแบนเนอร์",
    "Delete Banner": "ลบแบนเนอร์",
    "missing 'Image' field": "กรุณาเลือกไฟล์ 'รูปภาพ'",
    "missing 'Title' field": "กรุณากรอก 'ชื่อ'",
    "Add new banner success": "เพิ่มแบนเนอร์ใหม่สำเร็จ",
    "Edit banner success": "แก้ไขแบนเนอร์สำเร็จ",
    "Delete banner success": "ลบแบนเนอร์สำเร็จ",
    "Delete sub account success": "ลบบัญชีย่อยสำเร็จ",
    "Account-": "บัญชีผู้ใช้ :",
    "Deposit-": "ฝาก :",
    "Currency_": "สกุลเงิน :",
    "Withdrawal-": "ถอน :",
    "History Detail": "ประวัติรายละเอียด",
    "Agent": "เอเย่นต์",
    "Member": "สมาชิก",
    "Update deposit success": "บันทึกการฝากสำเร็จ",
    "Update withdrawal success": "บันทึกการถอนสำเร็จ",
    "DEPOSIT": "ฝาก",
    "WITHDRAWAL": "ถอน",
    "Save add new shareholder success": "บันทึกตัวแทนใหม่สำเร็จ",
    "Suspend-": "ระงับชั่วคราว :",
    "Lock-": "ล็อค :",
    "Edit status suspend, lock success": "แก้ไขสถานะระงับชั่วคราวสำเร็จ",
    "Edit sub account success": "แก้ไขบัญชีย่อยสำเร็จ",
    "Save add new sub account success": "บันทึกบัญชีย่อยใหม่สำเร็จ",
    "Edit agent success": "แก้ไขเอเย่นต์สำเร็จ",
    "Edit member success": "แก้ไขสมาชิกสำเร็จ",
    "Edit shareholder success": "แก้ไขตัวแทนสำเร็จ",
    "Save add new member success": "บันทึกสมาชิกใหม่สำเร็จ",
    "missing 'Bet Limit' field": "กรุณาเลือก 'วงเงินเดิมพัน'",
    "History Edit": "ประวัติการแก้ไข",
    "Online": "ออนไลน์ : ",
    "Min": "น้อยสุด",
    "Max": "มากสุด",
    "Invalid Currency": "กรุณากรอก 'สกุลเงิน'",
    "Bet Status": "สถานะการเดิมพัน",
    "Seamless Status": "สถานะ",
    "Request List": "รายการคำขอ",
    "Logs": "ข้อมูลบันทึก",
    "Edit by": "แก้ไขโดย",
    "textnumberonly": "กรอกได้เฉพาะตัวเลข (0-9) หรือตัวอักษร (A-Z, a-z) เท่านั้น",
    "numberonly": "กรอกได้เฉพาะตัวเลข (0-9)",
    "textTHnumberonly": "กรอกได้เฉพาะตัวเลข (0-9) หรือตัวอักษร (A-Z, a-z, ก-ฮ) เท่านั้น",
    "Invalid Username or Password": "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    "You've entered incorrect password too many times. Try again in 5 minutes.": "คุณใส่รหัสผ่านผิดเกินกำหนด กรุณาลองใหม่อีกครั้งหลัง 5 นาที",
    "Invalid captcha.": "รหัสผ่าน Captcha ไม่ถูกต้อง",
    "Dragon": "มังกร",
    "Tiger": "เสือ",
    "big": "ใหญ่",
    "bankerPair": "แบงค์เกอร์คู่",
    "bankerNatural": "แบงค์เกอร์ป๊อก",
    "playerNatural": "เพลย์เยอร์ป๊อก",
    "playerPair": "เพลย์เยอร์คู่",
    "small": "เล็ก",
    "super6": "ซุปเปอร์ซิก",
    "The old password you have entered is incorrect.": "รหัสผ่านเดิมที่คุณใส่ไม่ถูกต้อง",
    "Invalid input format 'password' field. (The password must have at least 8 characters.)": "รูปแบบการป้อนข้อมูลรหัสผ่านไม่ถูกต้อง (รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร)",
    "Invalid input format 'username' field. (The username must have at least 8 characters.)": "รูปแบบการป้อนข้อมูลชื่อผู้ใช้ไม่ถูกต้อง (ชื่อผู้ใช้ต้องมีอย่างน้อย 8 ตัวอักษร และห้ามมีตัวอักษรพิเศษ)",
    "Can't load report, because you refresh more than 30 times.": "ไม่สามารถดูรายงานได้ เนื่องจากคุณรีเฟชเกิน 30 ครั้ง กรุณาลองอีกครั้งในนาทีถัดไป",
    "Insufficient balance.": "ยอดเงินไม่เพียงพอ",
    "missing 'date' field": "กรุณาเลือก 'วันที่เริ่มต้น' และ 'ถึงวันที่'",
    "invalid bet limit parameter please input bet limit more than 1 but not more than 6 value.": "กรุณาเลือกวงเงินเดิมพันมากกว่า 1 รายการ และไม่เกิน 6 รายการ",
    "E11000 duplicate key error collection": "ชื่อผู้ใช้นี้มีอยู่แล้ว",
    "dragon": "มังกร",
    "tiger": "เสือ",
    "No.Ticket": "จำนวนตั๋ว",
    "Rate": "เรทคะแนน",
    "Comment": "ความคิดเห็น",
    "Network Connection": "การเชื่อมต่อเครือข่าย",
    "Video Quality": "คุณภาพวีดีโอ",
    "Our Girls": "สาวๆ ของเรา",
    "Graphic Design": "ออกแบบกราฟิค",
    "Customer Service": "บริการลูกค้า",
    "Member W/L": "สมาชิก แพ้ชนะ",
    "House Edge": "เปอร์เซนต์ชนะ",
    "Export Excel": "ดาวน์โหลด Excel",
    "ExportNote": "หมายเหตุ: สามารถดาวน์โหลดได้ครั้งละไม่เกิน 100 รายการเท่านั้น",
    "Login name not found.": "ไม่พบชื่อเข้าสู่ระบบ",
    "Tip Dealer": "ทิปดีลเลอร์",
    "Callback Dealer Tips": "ทิปดีลเลอร์",
    "Tips": "ทิป",
    "Type_": "ประเภท :",
    "Open": "เปิด",
    "Close": "ปิด",
    "Setting Baccarat": "ตั้งค่าบาคาร่า"
};

var Chinese = {
    "We are the future of gaming": "我们是游戏的未来",
    "Username": "用户名",
    "Password": "密码",
    "Captcha": "Captcha",
    "Sign in": "登入",
    "Contact your associate in case you forgot the password or unable to sign in": "如果您忘记密码或无法登入，请与您的代理联系。",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;手机版",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;使用说明书",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;登出",
    "Dashboard": "资讯主页",
    "Member Mngement": "会员管理",
    "Stock Mngement": "库存管理",
    "Balance info": "余额信息",
    "Today Turn Over": "今日下注洗码量",
    "Today Valid Turn Over": "今日下注金额",
    "Today Member Win Lose": "今日会员赢输报表",
    "Today Agent Win Lose": "今日代理赢输报表",
    "Yesterday Turn Over": "昨天下注洗码量",
    "Yesterday Valid Turn Over": "昨天下注金额",
    "Yesterday Member Win Lose": "昨天会员赢输报表",
    "Yesterday Agent Win Lose": "昨天代理赢输报表",
    "Total Outstanding Bets": "总下注余额",
    "Total Outstanding Balance": "总余额",
    "Members": "会员",
    "Agents": "代理",
    "Today": "今日",
    "Last Week": "上个星期",
    "Last Month": "上个月",
    "Outstanding": "未付款",
    "Your Downline": "您的下线",
    "New Members": "新会员",
    "Profile": "个人信息",
    "Basic Info": "基本信息",
    "Phone number": "电话号码",
    "Currency": "货币",
    "Credit": "信用",
    "Credit_": "信用 :",
    "PT": "占成比",
    "Original Baccarat": "传统百家乐",
    "Super6 Baccarat": "超六百家乐",
    "Bacarrat 4 Point": "四点百家乐",
    "Cow Cow": "牛牛",
    "Dragon Tiger": "龙虎",
    "Roulete": "轮盘",
    "Sicbo": "骰宝",
    "Thai Fan Tan": "Thai Fan Tan",
    "Original Baccarat_": "传统百家乐 :",
    "Super6 Baccarat_": "超六百家乐 :",
    "Bacarrat 4 Point_": "四点百家乐 :",
    "Cow Cow_": "牛牛 :",
    "Dragon Tiger_": "龙虎 :",
    "DragonTiger": "龙虎",
    "Dragon": "龙",
    "Tiger": "虎",
    "Roulete_": "轮盘 :",
    "Sicbo_": "骰宝 :",
    "Key": "代理商秘钥",
    "Callback url servlet": "回应连接",
    "Example https//www.yourcallback.com/service": "例如: https://www.yourcallback.com/service",
    "IP": "IP",
    "Example 192.168.0.1": "例如: 192.168.0.1",
    "Click to API Document": "点击进入API文件",
    "Add IP": "加IP",
    "Save Profile": "保存个人信息",
    "History login date & IP": "历史记录登录日期和IP",
    "Date": "日期",
    "IP address": "IP地址",
    "Commission": "佣金",
    "Change Password": "更改密码",
    "Save New Password": "保存新密码",
    "Add Sub Account": "添加子帐户",
    "Login name": "登录名",
    "Login name_": "登录名 :",
    "User_": "公司 :",
    "Search": "查询",
    "No": "顺数",
    "Nickname": "昵称",
    "Phone": "电话号码",
    "Edit": "编辑",
    "Lock": "锁",
    "Member": "会员",
    "Stock": "库存",
    "Report": "报表",
    "Last login date": "上次登录日期",
    "Last login IP": "上次登录IP",
    "Last login IP_": "上次登录IP :",
    "Permissions": "权限",
    "Off": "关闭",
    "View": "观看",
    "OFF": "关闭",
    "VIEW": "观看",
    "EDIT": "编辑",
    "Position": "位置",
    "Stake": "下注",
    "Turnover": "洗码量",
    "Company Total": "公司总金额",
    "Company": "公司",
    "Agent": "代理",
    "Agent (API)": "代理 (API)",
    "Total": "总金额 :",
    "Total-": "总金额",
    "Member Total": "会员总金额",
    "Agent Total": "代理总金额",
    "Event & Details": "活动及详情",
    "No data.": "没有数据",
    "Login date": "登录日期",
    "Login IP": "登录 IP",
    "Bet Type": "下注类型",
    "Bet Type_": "下注类型 :",
    "Bet": "下注",
    "Settle": "付款",
    "Seamless API": "单一钱包 API",
    "Recalculate": "重新计算",
    "Ticket ID": "下注单ID",
    "Ticket ID_": "下注单ID :",
    "Request / Response": "请求 / 回应",
    "Retry": "重试",
    "User Place Payout": "会员下注派彩接口",
    "User Place Bet Cancel": "会员取消下注接口",
    "User Place Bet": "会员下注接口",
    "Announcements": "公告",
    "Message": "信息",
    "Description": "说明",
    "Add Message": "加信息",
    "Add Message_": "<i class='fas fa-plus mr-1'></i>加信息",
    "Create date": "建立日期",
    "Create date_": "建立日期 :",
    "Modify date": "修改日期",
    "Update by": "更新者",
    "Delete": "删除",
    "Title": "标题",
    "Title_": "标题 :",
    "Banner": "旗帜",
    "Add Banner": "加旗帜",
    "Image": "图片",
    "Payment": "付款",
    "Deposit / Withdrawal": "存款 / 取款",
    "Credit": "信用",
    "Level": "等级",
    "Deposit": "存款",
    "Withdrawal": "取款",
    "Detail": "详情",
    "Account": "用户名",
    "Member Management": "会员管理",
    "Sub Accounts": "子账号",
    "Unlock": "解锁",
    "Stock Management": "库存管理",
    "Member Outstanding": "未付会员",
    "Statement": "财务报表",
    "Start date_": "开始日期 :",
    "To date_": "至...日期 :",
    "Action": "行动",
    "Total balance": "总金额",
    "Log": "记录",
    "All": "所有",
    "Previous": "以前",
    "Yesterday": "昨天",
    "This week": "这个星期",
    "Last week": "上个星期",
    "This month": "这个月",
    "Last month": "上个月",
    "Next": "下一个",
    "Description_": "说明 :",
    "Suspend": "暂停",
    "Level_": "等级 :",
    "Add Shareholder": "加股东",
    "Shareholder": "股东",
    "Shareholder (B2B)": "股东 (B2B)",
    "Shareholder (B2C)": "股东 (B2C)",
    "NoSus": "不是",
    "YesSus": "是",
    "Username-": "用户名<label style='color: red;'>&nbsp;*</label>",
    "Password-": "密码<label style='color: red;'>&nbsp;*</label>",
    "Currency-": "货币<label style='color: red;'>&nbsp;*</label>",
    "Credit-": "信用<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type-": "股东类型<label style='color: red;'>&nbsp;*</label>",
    "Shareholder type": "股东类型",
    "Our PT-": "我们的占成比<label style='color: red;'>&nbsp;*</label>",
    "Our PT": "我们的占成比",
    "Given PT-": "给定占成比<label style='color: red;'>&nbsp;*</label>",
    "Given PT": "给定占成比",
    "Original Baccarat-": "传统百家乐<label style='color: red;'>&nbsp;*</label>",
    "Super6 Baccarat-": "超六百家乐<label style='color: red;'>&nbsp;*</label>",
    "Bacarrat 4 Point-": "百家乐四点<label style='color: red;'>&nbsp;*</label>",
    "Cow Cow-": "牛牛<label style='color: red;'>&nbsp;*</label>",
    "Dragon Tiger-": "龙虎<label style='color: red;'>&nbsp;*</label>",
    "Roulete-": "轮盘<label style='color: red;'>&nbsp;*</label>",
    "Sicbo-": "骰宝<label style='color: red;'>&nbsp;*</label>",
    "Commission Setting": "设置佣金",
    "Credit Settings": "设置信用",
    "Edit Password": "修改密码",
    "Edit Status": "修改状态",
    "Edit Shareholder": "修改股东",
    "Status": "状态",
    "Members & Agents": "会员与代理",
    "Position type-": "位置类型<label style='color: red;'>&nbsp;*</label>",
    "Bet type-": "下注类型<label style='color: red;'>&nbsp;*</label>",
    "Add Agent": "加代理",
    "Edit Agent": "修改代理",
    "Position type": "位置类型",
    "Bet Limit-": "投注限额<label style='color: red;'>&nbsp;*</label>",
    "Bet Limit": "投注限额",
    "Add Member": "加会员",
    "Edit Member": "修改会员",
    "Add Banner_": "<i class='fas fa-plus mr-1'></i>加旗帜",
    "Transaction_": "交易 :",
    "W/L Member": "会员赢输报表",
    "W/L Game ID": "W/L Game ID",
    "W/L Company": "会员赢输报表",
    "Valid turn": "有效期至",
    "Amount": "合计",
    "Gross Comm": "总佣金",
    "Win lose": "赢输",
    "Comm": "佣金",
    "Information": "信息",
    "Result": "结果",
    "Credit/Cash": "信用/现金",
    "Partner": "股东",
    "Win/Loss & Comm & Total": "赢 输 &佣金& 总金额",
    "User": "用户名",
    "ID": "ID",
    "Game ID": "游戏 ID",
    "Game ID_": "游戏 ID :",
    "Baccarat": "百家乐",
    "tie": "和",
    "player": "闲",
    "banker": "庄",
    "Original": "传统",
    "Play Clip": "&nbsp;播放视频",
    "Before": "之前",
    "Win/Loss": "赢输",
    "After": "之后",
    "Lose": "输",
    "Win": "赢",
    "Tie": "和",
    "Player": "闲",
    "Banker": "庄",
    "Super6": "超六",
    "CowCow": "牛牛",
    "4Point": "四点",
    "Old Password": "旧密码<label style='color: red;'>&nbsp;*</label>",
    "New Password": "新密码<label style='color: red;'>&nbsp;*</label>",
    "Confirm Password": "确认密码<label style='color: red;'>&nbsp;*</label>",
    "missing 'Old Password' field": "请输入“旧密码”",
    "missing 'New Password' field": "请输入“新密码”",
    "missing 'Confirm Password' field": "请输入“确认密码”",
    "New password doesn't match confirm password": "新密码与确认密码不匹配",
    "Close": "关闭",
    "Change new password success": "密码修改成功",
    "Success": "成功",
    "Save profile success": "成功保存个人信息",
    "missing 'Username' field": "请输入“用户名”",
    "missing 'Password' field": "请输入”密码'",
    "missing 'Captcha' field": "Please enter 'Captcha'",
    "missing 'Currency' field": "请输入“货币”",
    "missing 'Credit' field": "请输入“贷方”",
    "Save add new agent success": "成功保存新代理",
    "Request By": "请求者",
    "Description-": "说明&nbsp;<label style='color: red;'>*</label>",
    "Save": "保存",
    "Edit Message": "修改信息",
    "Confirm delete this item ?": "确认删除此项目？",
    "Delete Message": "删除信息",
    "OK": "确认",
    "missing 'Description' field": "请输入“说明”",
    "Add new message success": "加新信息成功",
    "Edit message succes": "修改信息成功",
    "Delete message success": "删除信息成功",
    "Title-": "名字&nbsp;<label style='color: red;'>*</label>",
    "Image-": "图片&nbsp;<label style='color: red;'>*</label>",
    "Edit Banner": "修改旗帜",
    "Delete Banner": "删除旗帜",
    "missing 'Image' field": "请输入“图片”",
    "missing 'Title' field": "请输入“姓名”",
    "Add new banner success": "加新旗帜成功",
    "Edit banner success": "修改旗帜成功",
    "Delete banner success": "删除旗帜成功",
    "Delete sub account success": "删除子账号成功",
    "Account-": "用户名 :",
    "Deposit-": "存款 :",
    "Currency_": "货币 :",
    "Withdrawal-": "取款 :",
    "History Detail": "历史记录详细信息",
    "Agent": "代理",
    "Member": "会员",
    "Update deposit success": "成功保存存款",
    "Update withdrawal success": "成功保存提款",
    "DEPOSIT": "存款",
    "WITHDRAWAL": "取款",
    "Save add new shareholder success": "记录新股东成功",
    "Suspend-": "暂停 :",
    "Lock-": "锁定 :",
    "Edit status suspend, lock success": "修改状态暂停，锁定成功",
    "Edit sub account success": "修改子账号成功",
    "Save add new sub account success": "保存新子账号成功",
    "Edit agent success": "修改代理成功",
    "Edit member success": "修改会员成功",
    "Edit shareholder success": "修改股东成功",
    "Save add new member success": "保存新会员成功",
    "missing 'Bet Limit' field": "请输入“下注限制”",
    "History Edit": "历史修改记录",
    "Online": "线上 : ",
    "Min": "分",
    "Max": "最高",
    "Invalid Currency": "请输入“货币”",
    "Bet Status": "投注状态",
    "Seamless Status": "单一钱包状态",
    "Request List": "请求清单",
    "Logs": "记录",
    "Edit by": "编辑者",
    "textnumberonly": "仅输入数字（0-9）或字母（A-Z，a-z）。",
    "numberonly": "仅输入数字（0-9）。",
    "textTHnumberonly": "仅输入数字（0-9）或字母（A-Z，a-z，ก-ฮ）。",
    "Invalid Username or Password": "用户名或密码不正确。",
    "You've entered incorrect password too many times. Try again in 5 minutes.": "You've entered incorrect password too many times. Try again in 5 minutes.",
    "Invalid captcha.": "Invalid Captcha.",
    "big": "大",
    "bankerPair": "庄对",
    "bankerNatural": "庄例牌",
    "playerNatural": "闲例牌",
    "playerPair": "闲对",
    "small": "小",
    "super6": "超六",
    "The old password you have entered is incorrect.": "您输入的原始密码不正确。",
    "Invalid input format 'password' field. (The password must have at least 8 characters.)": "密码输入格式错误。 （密码必须至少8个字符）",
    "Invalid input format 'username' field. (The username must have at least 8 characters.)": "用户名格式错误。 （用户名必须至少包含8个字符，并且不允许使用特殊字符）",
    "Can't load report, because you refresh more than 30 times.": "无法刷新看报告，因为您刷新超过30次了。 请在1分钟后重试。",
    "Insufficient balance.": "余额不足",
    "missing 'date' field": "请选择“开始日期”和“截止日期”。",
    "invalid bet limit parameter please input bet limit more than 1 but not more than 6 value.": "请选择大于 1 个项目投注限额  但不可超过 6 个",
    "E11000 duplicate key error collection": "该用户名已经存在。",
    "dragon": "龙",
    "tiger": "虎",
    "No.Ticket": "票号",
    "Rate": "率",
    "Comment": "评论",
    "Network Connection": "网络连接",
    "Video Quality": "视频质量",
    "Our Girls": "我们的荷官",
    "Graphic Design": "图形化设计	",
    "Customer Service": "客户服务",
    "Member W/L": "会员 赢输报表",
    "House Edge": "胜率",
    "Export Excel": "下载Excel",
    "ExportNote": "备注：每次下载限制为100个项目",
    "Login name not found.": "找不到登录名",
    "Tip Dealer": "给消费荷官",
    "Callback Dealer Tips": "回调给荷官消费提示",
    "Tips": "提示",
    "Type_": "类型 :",
    "Open": "打开",
    "Close": "关闭",
    "Setting Baccarat": "百家乐设置"
};


